#!/usr/bin/env python
# encoding: utf-8

VERSION = '0.0.1'
APPNAME = 'hexapod_planner'

srcdir = '.'
blddir = 'build'

from waflib.Build import BuildContext
import sfml
import eigen


def options(opt):
    opt.load('compiler_cxx')
    opt.load('compiler_c')
    opt.load('sfml')
    opt.load('eigen')

def configure(conf):
    conf.load('compiler_cxx')
    conf.load('compiler_c')

    conf.get_env()['BUILD_GRAPHIC'] = False

    conf.load('sfml')
    conf.load('eigen')

    conf.check_sfml()
    conf.check_eigen()

    if conf.env.CXX_NAME in ["icc", "icpc"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -xHost  -march=native -mtune=native -unroll -fma -g"
    elif conf.env.CXX_NAME in ["clang"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"
    else:
        if int(conf.env['CC_VERSION'][0]+conf.env['CC_VERSION'][1]) < 47:
            common_flags = "-Wall -std=c++0x"
        else:
            common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"

    all_flags = common_flags + opt_flags
    conf.env['CXXFLAGS'] = conf.env['CXXFLAGS'] + all_flags.split(' ')
    print conf.env['CXXFLAGS']


def build(bld):
    d = []
    if bld.get_env()['BUILD_GRAPHIC'] == True:
        d = ['-DGRAPHIC']

    bld.program(features = 'cxx',
                  source = 'src/test.cpp',
                  includes = '. ./src',
                  uselib = 'SFML EIGEN',
                  cxxflags = d,
                  target = 'test_plain')

    bld.install_files('${PREFIX}/include/hexapod_planner', 'src/hexapod_planner_simple.hpp')
    bld.install_files('${PREFIX}/include/hexapod_planner', 'src/state_simple.hpp')
    bld.install_files('${PREFIX}/include/hexapod_planner', 'src/simple_env.hpp')
